# Constants: values that stay the same while the program runs, used for settings like titles, models, and configs
# Examples of constants:Page titles ,API URLs, Model names, Configuration settings. Constants are usually:Defined once, Reused throughout the code, Never modified during execution

[DEFAULT] # this is called as section
# This is a called as keys (configuration setting)
PAGE_TITLE = Langgraph : Build Stateful Agentic AI Graph 
LLM_OPTIONS = Groq
USECASE_OPTIONS = Basic Chatbot, Chatbot with tool
GROQ_MODEL_OPTIONS = llama-3.1-8b-instant, llama-3.3-70b-versatile, openai/gpt-oss-120b, openai/gpt-oss-20b